name: CI Pipeline

on:
  push: {}
  pull_request: {}

jobs:
  lint:
    name: Lint with Pylint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Pylint
        run: pylint src

  cli_tests:
    name: BDD CLI tests (Cucumber+Aruba)
    needs: lint
    runs-on: ubuntu-latest
    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Python deps
        run: pip install -r requirements.txt
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Create Gemfile
        run: |
          cat << 'EOF' > Gemfile
          source "https://rubygems.org"
          gem "cucumber", "~> 9.2"
          gem "aruba",    "~> 2.3"
          EOF
      - name: Bundle install
        run: bundle install --jobs 4 --retry 3
      - name: Run Cucumber features
        run: |
          bundle exec cucumber \
          --require features \
          --require aruba/cucumber \
          --tags "not @wip" \
          --format pretty

  stress:
    name: Stress tests
    needs: cli_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run stress tests
        run: python -m pytest tests/stress_test.py

  stdin_stress:
    name: Stress stdin
    needs: stress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run stdin stress tests
        run: python tests/stress_stdin.py

  valgrind:
    name: Memory check with Valgrind
    needs: stdin_stress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind
      - name: Run Valgrind
        uses: Ximaz/valgrind-action@v1.2.0
        with:
          binary_path: "python"
          binary_args: "src/app.py greet --name CI"

  profiling:
    name: Time profiling
    needs: valgrind                    # ← дождётся окончания Valgrind
    runs-on: ubuntu-latest             # ← тот же раннер
    steps:
      - uses: actions/checkout@v4
      - name: Profile execution time
        run: |
          /usr/bin/time -f "real %e user %U sys %S" \
            python src/app.py greet --name CI 2> time.log
          cat time.log